apiVersion: v1
kind: Service
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  type: NodePort
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    - name: "4445"
      port: 4445
      targetPort: 4445
  selector:
   app: hydra
