apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-api-config
  labels:
    app: oathkeeper-api-config
data:
  LOG_LEVEL: debug
  ISSUER_URL: http://oathkeeper-proxy:4455/
  AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL: http://hydra:4444/oauth2/token
  AUTHENTICATOR_OAUTH2_INTROSPECTION_URL: http://hydra:4445/oauth2/introspect
  AUTHORIZER_KETO_WARDEN_KETO_URL: http://keto:4466
  CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
  CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL: http://hydra:4445
  CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID: resources:hydra:jwk:oathkeeper
  CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL: 30m
  CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN: 1h
