apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hydra-migrate
        image: 'oryd/hydra'
        imagePullPolicy: "IfNotPresent"
        command: ["hydra"]
        args:
          - migrate
          - sql
          - postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
        envFrom:
          - configMapRef:
              name: hydra-migrate-config
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
