apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-proxy
  labels:
    app: oathkeeper-proxy
spec:
  type: NodePort
  ports:
    - name: "4455"
      port: 4455
      targetPort: 4455
  selector:
   app: oathkeeper-proxy
